### ISSUE TITLE
Harmonize map conversion to image

### ISSUE THREAD

**Issue by ipa-rmb** [ipa320/autopnp#10]
Read out the map properly during conversion into image format. The map coordinate system start at the lower left corner, but the cell data array starts in the upper left corner, moving right then downwards. This has to be cleanly converted to the cv image to employ the results obtained from the image properly to real world map coordinates (especially the angles are affected).

**Comment by qingchunlizhi** [comment]
Why this A* planner plans a path going through the black area ? 
![image](https://user-images.githubusercontent.com/18531375/82173122-ce640d00-98fe-11ea-91bc-e02855ecf15b.png)

**Comment by ipa-rmb** [comment]
The planner is not planning to go through the black area. This visualization just contains the path points indicated by a "+" sign, whereas the connecting line between two trajectory points of the path is just drawn as a line for visualization purposes. The actual path depends on your utilized path planner (navigation system) or you just run the A* planner for drawing the real path connecting two points as well. I think there is even a visualization option (maybe commented out in the code) showing the actual A* paths - please have a look for that in the code on your own. At least, all planning uses A* paths even if not visualized accordingly.
