### ISSUE TITLE
Compiled `ipa_room_segmentation` on melodic

### ISSUE THREAD

**Issue by corot** [ipa320/autopnp#20]
I have [forked](https://github.com/corot/autopnp) this repo from ipa-rmb/autopnp and changed to compile `ipa_room_segmentation` on melodic. Seems to work so far. I'm not interested by now in the other packages, but if the maintainers have interest, I can try to make the other packages compile and PR here.

**Comment by eborghi10** [comment]
It seems like the package is [here](https://github.com/ipa320/ipa_coverage_planning/tree/indigo_dev/ipa_room_segmentation) and it's working for ROS Melodic!

**Comment by corot** [comment]
Looks more recent, but still cannot compile directly on melodic. as with autopnp code, catkin cannot find libdlib (it's installed, but it lacks .cmake file)

```
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "libdlib" with any
  of the following names:

    libdlibConfig.cmake
    libdlib-config.cmake
```

**Comment by eborghi10** [comment]
Have to tried to install the dependencies before?
```
rosdep install --from-path src -yi
```

**Comment by corot** [comment]
Yes, but rosdep cannot find neither libdlib nor opengm:
```
ipa_room_segmentation: Cannot locate rosdep definition for [opengm]
ipa_room_segmentation: Cannot locate rosdep definition for [libdlib]
```
Package libdlib-dev actually exists, though it cannot be located by CMake. But opengm doesn't

**Comment by lmanfredi** [comment]
try	
sudo apt-get install ros-melodic-libdlib
sudo apt-get install ros-melodic-opengm

**Comment by corot** [comment]
:+1:    it worked!  Thanks!
Would be nice to drop the repeated pkgs from this repo, and point to https://github.com/ipa320/ipa_coverage_planning instead
